#ifndef CONFIG_H
#define CONFIG_H

#define SENSOR_COUNT 5U
#define FEATURE_COUNT 5U
#define WINDOW_LENGTH 16U
#define MODEL_INPUT_SIZE (SENSOR_COUNT * WINDOW_LENGTH)

#define CONFIRMATION_COUNT 3U

#endif